[package]
name = "pyth_lazer"
version = "0.0.0"
edition = "2024"
published-at = "0xfa65b0da732c85c34bda6504e367d6a800f1816798573268dd0931653bb8e375"

[dependencies.wormhole]
local = "../../../target_chains/sui/vendor/wormhole_lazer/wormhole"