[package]
name = "pyth_lazer"
version = "0.0.0"
edition = "2024"
published-at = "0x3b4d58cacd16a46f90a327127c5a2f3753ebc18a0fb2a6d4b8936be2280f68da"

[dependencies.wormhole]
local = "../../../target_chains/sui/vendor/wormhole_lazer/wormhole"