[package]
name = "Pyth"
version = "0.0.2"
published-at = "0xabf837e98c26087cba0883c0a7a28326b1fa3c5e1e2c5abdb486f9e8f594c837"

[dependencies.Wormhole]
git = "https://github.com/Typus-Lab/wormhole.git"
subdir = "sui/wormhole"
rev = "testnet"

[addresses]
pyth = "0xabf837e98c26087cba0883c0a7a28326b1fa3c5e1e2c5abdb486f9e8f594c837"
